server:
  port: 8888
  
security:
  user:
    password: s3cret

encrypt:
  key: foobar

spring:
  application:
    name: configserver
  config:
    name: configserver 
  profiles:
    active: native
  cloud:
    config:
      enabled: true
      server:
        native:
          searchLocations: 
            classpath:/config